services:
  db:
    image: postgres:15-alpine
    container_name: opticretail_db
    environment:
      POSTGRES_USER: optic_user
      POSTGRES_PASSWORD: optic_password
      POSTGRES_DB: optic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: https://github.com/Kr1sh-gupta/OpticRetail.git#backend
    container_name: opticretail_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://optic_user:optic_password@db:5432/optic_db
      - ENVIRONMENT=production
      
  frontend:
    build: https://github.com/Kr1sh-gupta/OpticRetail.git#frontend
    container_name: opticretail_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
