services:
  db:
    image: postgres:15-alpine
    container_name: opticretail_db
    environment:
      POSTGRES_USER: optic_user
      POSTGRES_PASSWORD: optic_password
      POSTGRES_DB: optic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: https://github.com/Kr1sh-gupta/OpticRetail.git#backend
    container_name: opticretail_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://optic_user:optic_password@db:5432/optic_db
      - ENVIRONMENT=production
      - CAM1_SOURCE=/CCTV_Footage/CAM 1.mp4
      - CAM2_SOURCE=/CCTV_Footage/CAM 2.mp4
      - CAM3_SOURCE=/CCTV_Footage/CAM 3.mp4
      - CAM4_SOURCE=/CCTV_Footage/CAM 4.mp4
      - CAM5_SOURCE=/CCTV_Footage/CAM 5.mp4
    volumes:
      - "../CCTV Footage:/CCTV_Footage"
      
  frontend:
    build: https://github.com/Kr1sh-gupta/OpticRetail.git#frontend
    container_name: opticretail_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
